[package]
name = "webscreen-rs"
version = "0.1.0"
authors = ["kiwiyou <kiwiyou.dev@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7"
base64 = "0.10"
config = "0.9"
futures = "0.1"
scrap = "0.5"
repng = "0.2"
env_logger = "0.6"
log = "0.4"